defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *defaults
  database: synergy-croatia_development

test:
  <<: *defaults
  database: synergy-croatia_test

production:
  <<: *defaults
  database: synergy-croatia_production
