defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: warning

development:
  <<: *defaults
  database: synergy-croatia_development

test:
  <<: *defaults
  database: synergy-croatia_test

staging:
  <<: *defaults
  database: synergy-croatia_staging

production:
  <<: *defaults
  database: synergy-croatia_production
