development: &development
  app_key: <%= ENV["DROPBOX_APP_KEY"] %>
  app_secret: <%= ENV["DROPBOX_APP_SECRET"] %>
  access_token: <%= ENV["DROPBOX_ACCESS_TOKEN"] %>
  access_token_secret: <%= ENV["DROPBOX_ACCESS_SECRET"] %>
  access_type: "app_folder"
test:
  <<: *development
